### PR TITLE
added oauth provider functionality through Doorkeeper gem

### PR DESCRIPTION
**Pull request by akstuhl**
installed doorkeeper gem; added a bare-bones API controller/view to pass needed user info to the Idea Space app

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Looks great, @akstuhl! Not that I'm reviewing Annotation Studio PRs, but... :metal:! Can't wait for a demo.

**Comment by akstuhl** [comment]
Thanks, @jamiefolsom! Excited to show you the new stuff.

**Comment by NickLaiacona** [comment]
Hi Andy, is there a staging server where we can see this feature in action? Kurt and I discussed having my QA staff give a test. Also, is there any documentation on what it should do? Which SSO providers should we expect it to work with, how it works with the existing authentication system, etc?

**Comment by akstuhl** [comment]
Hi @NickLaiacona, thanks for taking a look! I'm not sure of the current status of the staging server for Annotation Studio, but I'll try to deploy that so that your team can test it. This PR sets Annotation Studio itself up as an SSO provider, specifically so that the Idea Space app can route user sign-in through Annotation Studio. The only changes made to Annotation Studio are Doorkeeper's configuration (https://github.com/doorkeeper-gem/doorkeeper#configuration) and API protection (https://github.com/doorkeeper-gem/doorkeeper#protecting-resources-with-oauth-aka-your-api-endpoint) steps, as well as adding in a minimal API view to pass user info to Idea Space once the user authorizes it. Over on the Idea Space side (not in this PR), I've used the Devise OmniAuth module (http://devise.plataformatec.com.br/#omniauth) and created a gem that implements an OmniAuth strategy to interface with Annotation Studio as an OAuth 2.0 provider (https://github.com/hyperstudio/Idea-Space/tree/master/vendor/omniauth-annotation-studio), so that's what the API and Doorkeeper configuration are tailored to.

**Comment by akstuhl** [comment]
Hi @NickLaiacona, I've deployed this branch to a staging server at http://annotationstudio-staging-hs-t.herokuapp.com. The authentication workflow can be tested by signing into Annotation Studio on the staging server, then visiting https://annotation-studio-idea-space.herokuapp.com and clicking "Login with Annotation Studio" in the upper righthand corner.

**Comment by NickLaiacona** [comment]
Thank you for setting up a demo environment, it looks good.

**Pull request merged**
