### PR TITLE
Merge forks in preparation for release.

### PR DESCRIPTION
**Pull request by NickLaiacona**
This is a pull request to get the main Annotation Studio repo up to date with the forks from Performant and Hofstra DRC. This includes the work on tags, groups, categories, and MEL Catalog integration over the last eight months or so. MEL Cat and Category features can be enabled or disabled on a per tenant basis from the admin control panel.

### CODE REVIEW

**Comment by NickLaiacona** [comment]
@jamiefolsom , this version is presently running on staging if you care to kick the tires: staging-annotationstudio.herokuapp.com . I'm going to do another pull request on the annotation store that works with this version of the app.

**Comment by jamiefolsom** [comment]
@NickLaiacona Thanks!

**Comment by jamiefolsom** [comment]
Hey @NickLaiacona; I would be glad to offer a review of this PR, but it would have to be off-hours, and I don't want to hold you up if you're looking to merge it ASAP.

**Comment by jamiefolsom** [comment]
@NickLaiacona couple of quick suggestions; your discretion as to whether they're useful: -- squashing commits into logical chunks, and rebasing on master (if you haven't already).

**Comment by NickLaiacona** [comment]
@jamiefolsom good suggestions and in the future I hope that rebasing and rolling up commits into more meaningful packages (such as epics or user stories) could be done in the future as that work is being done.

**Pull request merged**
